sudo: required
services:
  - docker 
env:
  global: # get the current shaw to our enviroment 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # all pre configured files for google cloud inn order for it to work as excpected
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project light-result-277116 #enter tehe name of the project here 
  - gcloud config set compute/zone us-central1-a	#location of the compute for kubernetes
  - gcloud container clusters get-credentials multi-cluster #project name
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t orirothschild/react-test -f ./client/Dockerfile.dev ./client #the build context means what other files we wish to instert to our created image
  #like react files to run a react app etc

script:
  - docker run -e CI=true orirothschild/multi-container-react-test npm test 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master


